name: Docker CI

on:
  push:
    paths:
      - App/**
  pull_request:
    paths:
      - App/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd app
          docker build -t node-api:ci .